(()=>{
  // CONIUNCTIO β.4 metabolitza β.1–β.3: una sola memòria, una sola fisiologia.
  const KEY='animic-universe-travessa-v3';
  const OLD_KEYS=['animic-universe-travessa-v2','animic-presence-trail'];
  const $=s=>document.querySelector(s);
  const routes={listen:{organ:'Rosa de l’Escolta',phenomenon:'escolta',return:'Alguna cosa encara demana ser escoltada.'},act:{organ:'Instrument Z',phenomenon:'diferència',return:'Una diferència anterior encara deixa rastre.'},wait:{organ:'Cambra nua del temps',phenomenon:'absència',return:'Alguna cosa encara sosté el temps.'},trace:{organ:'STRATUM',phenomenon:'genealogia',return:'Una genealogia anterior encara demana ser contrastada.'},custody:{organ:'Archivum · Custòdia',phenomenon:'custòdia',return:'Allò verificat conserva on és; allò absent continua visible.'},error:{organ:'Compost',phenomenon:'error fèrtil',return:'Allò que va fallar encara no ha acabat de dir què era.'},lost:{organ:'Centre',phenomenon:'desorientació',return:'No tota desorientació necessita una direcció immediata.'}};
  const relations={'absència|escolta':{label:'absència ↔ escolta',text:'Potser ara s’escolta una altra cosa.'},'escolta|diferència':{label:'escolta ↔ diferència',text:'La diferència ja té un abans.'},'error fèrtil|diferència':{label:'error fèrtil ↔ diferència',text:'No reparis encara aquesta diferència.'},'absència|diferència':{label:'absència ↔ diferència',text:'El que no apareix també modifica.'},'desorientació|escolta':{label:'desorientació ↔ escolta',text:'No tenir direcció pot obrir l’escolta.'},'escolta|absència':{label:'escolta ↔ absència',text:'Potser el que importa és el que falta.'}};
  let pending=null;
  const valid=x=>Array.isArray(x)?x.filter(r=>r&&routes[r.gesture]&&typeof r.at==='string').slice(-8):[];
  function load(){try{const v3=valid(JSON.parse(localStorage.getItem(KEY)||'[]'));if(v3.length)return v3;const v2=valid(JSON.parse(localStorage.getItem(OLD_KEYS[0])||'[]'));if(v2.length){localStorage.setItem(KEY,JSON.stringify(v2));return v2}}catch{}return[]}
  const memory=load();
  function save(){try{localStorage.setItem(KEY,JSON.stringify(memory.slice(-8)));OLD_KEYS.forEach(k=>localStorage.removeItem(k))}catch{}}
  function relationFor(){if(memory.length<2)return null;const a=memory.at(-2)?.phenomenon,b=memory.at(-1)?.phenomenon;if(!a||!b||a===b)return null;return relations[`${a}|${b}`]||null}
  function applyPresenceMemory(){const last=memory.at(-1),lead=$('#presence .lead');document.title='Anímic Protein Universe · Navegació Presencial β.4 · CONIUNCTIO';if(last&&lead){lead.textContent=routes[last.gesture]?.return||'Alguna cosa de la travessa anterior encara hi és.';lead.dataset.memory='1'}if(memory.length)$('#mapToggle')?.classList.add('revealed')}
  function captureGesture(target){const g=target?.dataset?.gesture;if(g&&routes[g])pending=g;else if(target?.id==='traceBtn')pending='trace';else if(target?.id==='custodyBtn')pending='custody';else if(target?.id==='errorBtn')pending='error';else if(target?.id==='lostBtn')pending='lost'}
  function disableAnt(){const ant=$('#ant');if(!ant)return;ant.classList.remove('show');ant.setAttribute('aria-hidden','true');ant.removeAttribute('role');ant.removeAttribute('tabindex');ant.removeAttribute('aria-label');ant.removeAttribute('title');ant.onclick=null;ant.onkeydown=null}
  function activateAnt(rel){const ant=$('#ant');if(!ant)return;ant.classList.add('show');ant.setAttribute('aria-hidden','false');ant.setAttribute('role','link');ant.setAttribute('tabindex','0');ant.setAttribute('aria-label',`Seguir relació ${rel.label}`);ant.title='Seguir aquesta relació';const follow=()=>{location.href=`../inter-nos-creative/?relation=${encodeURIComponent(rel.label)}&from=universe-coniunctio-beta4`};ant.onclick=follow;ant.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();follow()}}}
  function commitTrace(){if(!pending||!routes[pending])return;const r=routes[pending],last=memory.at(-1),duplicate=last&&last.gesture===pending&&Date.now()-Date.parse(last.at)<1500;if(!duplicate){memory.push({gesture:pending,organ:r.organ,phenomenon:r.phenomenon,at:new Date().toISOString()});while(memory.length>8)memory.shift();save()}const rel=relationFor(),after=$('#after'),text=$('#returnText');after?.classList.add('show');$('#mapToggle')?.classList.add('revealed');if(rel){activateAnt(rel);if(text)text.textContent=rel.text;document.documentElement.dataset.animicPhenomenon=rel.label}else{disableAnt();if(text)text.textContent='Rastre deixat.';delete document.documentElement.dataset.animicPhenomenon}}
  function installTrace(){const trace=$('#trace');if(trace)trace.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();commitTrace()},true)}
  function installReset(){const reset=$('#reset');if(reset)reset.addEventListener('click',()=>{pending=null;disableAnt();delete document.documentElement.dataset.animicPhenomenon},true)}
  function installForget(){const reset=$('#reset');if(!reset||$('#forgetTravessa'))return;const b=document.createElement('button');b.id='forgetTravessa';b.className='quiet';b.type='button';b.textContent='Oblidar la travessa';b.style.opacity='.48';b.onclick=()=>{try{localStorage.removeItem(KEY);OLD_KEYS.forEach(k=>localStorage.removeItem(k))}catch{}memory.splice(0);pending=null;delete document.documentElement.dataset.animicPhenomenon;const lead=$('#presence .lead');if(lead){lead.textContent='Entra. L’organisme no et mostrarà tot el que té: només allò que pugui ser pertinent ara.';delete lead.dataset.memory}disableAnt();$('#mapToggle')?.classList.remove('revealed')};reset.insertAdjacentElement('afterend',b)}
  document.addEventListener('click',e=>captureGesture(e.target),true);save();applyPresenceMemory();installTrace();installReset();installForget();disableAnt();
})();