import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),failures=[];const normalizeLocal=ref=>ref.split(/[?#]/,1)[0].replace(/^\.\//,'');
const app=read('app.js');const scriptRefs=[...app.matchAll(/'\.\/(.+?\.js)'/g)].map(m=>m[1]),loadedScriptRefs=scriptRefs.filter(ref=>ref!=='sw.js');for(const ref of scriptRefs)if(!exists(ref))failures.push('app.js referencia un script inexistent: '+ref);
const sw=read('sw.js');const assetRefs=[...sw.matchAll(/'\.\/(.*?)'/g)].map(m=>m[1]).filter(Boolean);for(const ref of assetRefs)if(ref&&ref!=='.'&&!exists(ref))failures.push('sw.js referencia un recurs inexistent: '+ref);
for(const marker of ["url.includes('/fusio-total/')","if(url.includes('/fusio-total/'))return caches.match('./fusio-total/index.html')"])if(!sw.includes(marker))failures.push('El mode offline no preserva la recepció de MUTATIO: '+marker);
const html=read('index.html');for(const marker of ['class="threshold"','class="enter"','href="./universe/"','formiga.css','formiga.js'])if(!html.includes(marker))failures.push('El llindar canònic no conté el marcador actual: '+marker);
for(const file of ['cartographia-mutabilis/index.html','cartographia-mutabilis/cartographia.css','cartographia-mutabilis/cartographia.js','governanca/CARTOGRAPHIA_MUTABILIS_RECUPERACIO_1.0.md','governanca/CARTOGRAPHIA_MUTABILIS_CONSTELLACIO_VIVA_1.2.md'])if(!exists(file))failures.push('Cartographia Mutabilis recuperada incompleta: falta '+file);
if(exists('cartographia-mutabilis/index.html')){const c=read('cartographia-mutabilis/index.html');for(const marker of ['MAPA VIU · CARTOGRAPHIA MUTABILIS','SET CONSTEL·LACIONS FUNDACIONALS','relacionar ≠ canonitzar','id="relations"','../universe/','../stratum/','../inter-nos-creative/'])if(!c.includes(marker))failures.push('Cartographia Mutabilis no preserva identitat, límit o retorn: '+marker);}
if(exists('cartographia-mutabilis/cartographia.js')){const c=read('cartographia-mutabilis/cartographia.js');for(const marker of ["state:known?'canònica':'emergent'","state:'sembrada'","slice(0,24)",'localStorage.removeItem(storageKey)',"queue.length<5","queue.length<3||queue.length>5","humanDecision:decision","decision==='quiet'","kind:'constellation'","source:'Cartographia Mutabilis 1.2'","causality:{","resonance:{","hypothesis:{","reciprocity:{","tension:{"])if(!c.includes(marker))failures.push('Cartographia Mutabilis no preserva constel·lació, decisió o reversibilitat: '+marker);if(/fetch\(|XMLHttpRequest|sendBeacon|WebSocket/i.test(c))failures.push('Cartographia Mutabilis no pot transmetre relacions locals.');}
if(exists('governanca/CARTOGRAPHIA_MUTABILIS_CONSTELLACIO_VIVA_1.2.md')){const c=read('governanca/CARTOGRAPHIA_MUTABILIS_CONSTELLACIO_VIVA_1.2.md');for(const marker of ['relacionar ≠ canonitzar; proposar ≠ decidir','suggestedFigure → humanDecision → local trace','tres a cinc nodes','PROVISIONAL / HUMAN-DECIDED / LOCAL-ONLY / REVERSIBLE'])if(!c.includes(marker))failures.push('Contracte Constel·lació Viva 1.2 incomplet: '+marker);}
if(exists('governanca/CARTOGRAPHIA_MUTABILIS_RECUPERACIO_1.0.md')){const c=read('governanca/CARTOGRAPHIA_MUTABILIS_RECUPERACIO_1.0.md');for(const marker of ['No és un territori, un òrgan, una autoritat, una memòria paral·lela','commit `95e5b74`','mostrar ≠ relacionar; relacionar ≠ decidir; decidir ≠ canonitzar','RECOVERED / NON-CANONIZING / REVERSIBLE'])if(!c.includes(marker))failures.push('Contracte de recuperació de Cartographia incomplet: '+marker);}
if(!exists('universe/index.html'))failures.push('Falta la navegació presencial universe/index.html.');else{const universe=read('universe/index.html');for(const id of ['stage','organ','trace','ant','returnText'])if(!universe.includes('id="'+id+'"')&&!universe.includes("id='"+id+"'"))failures.push('La navegació presencial no conté #'+id);}if(!exists('universe/travessa-beta2.js'))failures.push('Falta el motor de travessa del Universe.');else{const travessa=read('universe/travessa-beta2.js');for(const marker of ["trace:{organ:'STRATUM'","custody:{organ:'Archivum · Custòdia'","target?.id==='traceBtn'","target?.id==='custodyBtn'","Navegació Presencial β.4"])if(!travessa.includes(marker))failures.push('La travessa del Universe no preserva el retorn operatiu: '+marker);}
if(!exists('universe/llenguatge/index.html'))failures.push('Falta la constel·lació Llenguatge Viu.');else{const language=read('universe/llenguatge/index.html'),universe=read('universe/index.html');for(const marker of ['Vocabulari Viu','Llatinismes','Glossae Viventes','../../beta/travesses/eco-01/','../../experiments/kreator-rpg/','../../cambra-nua-2/'])if(!language.includes(marker))failures.push('Llenguatge Viu no preserva el pilot: '+marker);for(const marker of ['id="languageLink"','href="./llenguatge/"','no decideix'])if(!universe.includes(marker))failures.push('Universe no exposa Llenguatge Viu com a constel·lació: '+marker);if(/suggestedImpulse|humanDecision|localStorage/.test(language))failures.push('Llenguatge Viu no pot proposar, decidir ni crear memòria operativa.');}if(!exists('governanca/LLENGUATGE_VIU_PILOT_1.0.md'))failures.push('Falta el contracte del pilot Llenguatge Viu.');else{const languageContract=read('governanca/LLENGUATGE_VIU_PILOT_1.0.md');for(const marker of ['No és un òrgan nou','no emet `suggestedImpulse`','no registra `humanDecision`','ECO 01','KREATOR RPG 0.4.5','Cambra Nua del Temps'])if(!languageContract.includes(marker))failures.push('El contracte Llenguatge Viu no preserva el límit transversal: '+marker);}
{const universe=read('universe/index.html');for(const marker of ['id="conviviumLink"','../experiments/kreator-rpg/seguiment/','CONVIVIUM','reuneix sense fusionar'])if(!universe.includes(marker))failures.push('Universe no exposa CONVIVIUM com a capa relacional: '+marker);}
if(!exists('universe/impuls.js'))failures.push('Falta IMPULS 1.2.');else{const impulse12=read('universe/impuls.js');for(const marker of ["IMPULS · 1.2","animic.codex.impulse-decisions/v1","suggestedImpulse","humanDecision","acceptedSuggestion","basis","subjectRef","subjectBinding","codex:human-decision","writeDecision(record);","location.assign(target)","initiatedAt","filter(item=>item?.id!==record.id)"])if(!impulse12.includes(marker))failures.push('IMPULS 1.2 no preserva subjecte i decisió: '+marker);const writeAt=impulse12.indexOf('writeDecision(record);'),navigateAt=impulse12.indexOf('location.assign(target)');if(writeAt<0||navigateAt<0||writeAt>navigateAt)failures.push('IMPULS 1.2 navega abans de conservar la decisió humana.');}
if(!exists('fusio-total/mutatio-receptor.js'))failures.push('Falta el receptor 0.2 de MUTATIO.');else{const receptor=read('fusio-total/mutatio-receptor.js');for(const marker of ["const VERSION='0.2'","animic.codex.impulse-decisions/v1","animic.codex.mutatio-receptions/v1","latestDecision()","humanDecision?.action==='transform'","effect?.initiated===true","decision.humanDecision?.subjectRef||null","if(!subjectRef)","Sense subjecte no hi ha transformació.","'instrument-z'","'compost'","pending","codex:mutatio-reception-resolved","canonical:false","reversible:true"])if(!receptor.includes(marker))failures.push('MUTATIO 0.2 no preserva el llindar de subjecte: '+marker);}const fusio=read('fusio-total/index.html');for(const marker of ['./mutatio-receptor.js','id="z"','id="compost"','window.addEventListener("hashchange", activateHash)','id === "z"','id === "compost"'])if(!fusio.includes(marker))failures.push('Fusió Total no resol un destí real de MUTATIO: '+marker);
if(!exists('governanca/REENTRADA_SUBJECTE_1.0.md'))failures.push('Falta el contracte REENTRADA 1.0 · Subjecte.');else{const reentry=read('governanca/REENTRADA_SUBJECTE_1.0.md');for(const marker of ['suggestedImpulse.basis','humanDecision.subjectRef','subjectBinding: bound|unbound','Sense subjecte no hi ha transformació'])if(!reentry.includes(marker))failures.push('REENTRADA 1.0 no preserva el contracte de subjecte: '+marker);}const bridge=JSON.parse(read('pont-site.json'));if(bridge.governance?.current_construction!=='kreator1_sessio01_ordre_causal_1_1'||bridge.governance?.reentry_contract?.impuls!=='1.2'||bridge.governance?.reentry_contract?.mutatio_receptor!=='0.2'||bridge.governance?.reentry_contract?.subject_required_before_destination!==true||bridge.governance?.reentry_contract?.kreator_session!=='1.1-causal'||bridge.governance?.reentry_contract?.master_optional_before_human_decision!==true)failures.push('PONS no preserva REENTRADA 1.0 ni declara KREATOR 1.1 causal.');
const localRefs=[...html.matchAll(/(?:href|src)=["']([^"']+)["']/g)].map(m=>m[1]).filter(ref=>!ref.startsWith('#')&&!/^(?:https?:|data:|mailto:|tel:)/.test(ref));for(const ref of localRefs){const target=normalizeLocal(ref);if(target&&!exists(target))failures.push('index.html referencia un recurs inexistent: '+ref);}const fragmentRefs=[...html.matchAll(/href=["']#([^"']+)["']/g)].map(m=>m[1]);for(const id of fragmentRefs)if(!html.includes('id="'+id+'"')&&!html.includes("id='"+id+"'"))failures.push('index.html referencia un fragment inexistent: #'+id);
let manifest;try{manifest=JSON.parse(read('manifest.webmanifest'))}catch{failures.push('manifest.webmanifest no és JSON vàlid.');}if(manifest){if(manifest.start_url!=='./'||manifest.scope!=='./')failures.push('El manifest ha de mantenir start_url i scope relatius a l’arrel canònica.');for(const icon of manifest.icons||[]){const target=normalizeLocal(icon.src||'');if(!target||!exists(target))failures.push('El manifest referencia una icona inexistent: '+(icon.src||'(buida)'));}}for(const ref of loadedScriptRefs)if(!assetRefs.includes(ref))failures.push('El mode offline no inclou el script carregat: '+ref);for(const ref of localRefs.map(normalizeLocal).filter(Boolean))if(!assetRefs.includes(ref)&&ref!=='sw.js')failures.push('El mode offline no inclou el recurs de la portada: '+ref);
for(const file of ['governanca/ARQUITECTURA.md','governanca/FUSIO_REPOSITORIS.md'])if(/`Animic-Protein\/Animic-Protein`/.test(read(file)))failures.push(file+' encara declara el repositori previ com a tronc canònic.');if(!exists('LICENSE.md'))failures.push('Falta la llicència canònica LICENSE.md.');else{const license=read('LICENSE.md');for(const marker of ['LICENSE_STATUS: FINAL-RR-1.0','Copyright © 2026 Dàrius Balboa','permís escrit previ','Contribucions'])if(!license.includes(marker))failures.push('LICENSE.md no conté el marcador canònic: '+marker);if(/LICENSE_STATUS:\s*PENDING/i.test(license))failures.push('La llicència encara consta com a pendent.');}if(!exists('governanca/DECISIO_LLICENCIA_2026-08-27.md'))failures.push('Falta l’acta de decisió de la llicència definitiva.');const allJs=fs.readdirSync(root).filter(n=>n.endsWith('.js'));if(!allJs.includes('core.js')||!allJs.includes('germinacio.js'))failures.push('Falten fitxers crítics del nucli.');
for(const file of ['recordare/index.html','recordare/recordare.js','recordare/invocatio.js','governanca/RECORDARE_1.0.md'])if(!exists(file))failures.push('RECORDARE incomplet: falta '+file);if(exists('recordare/recordare.js')){const r=read('recordare/recordare.js');for(const marker of ["getUserMedia({audio:true})","localOnly:true","canonical:false","binaryTransferred:false","codex:recordare-metadata-ready"])if(!r.includes(marker))failures.push('RECORDARE no preserva el contracte: '+marker);if(/airtable\.com|apiKey|AIRTABLE_TOKEN/i.test(r))failures.push('RECORDARE client no pot contenir connexió o credencials Airtable.');}if(exists('recordare/invocatio.js')&&!read('recordare/invocatio.js').includes('codex:recordare-metadata-ready'))failures.push('Invocatio no retorna les metadades preparades al context invocador.');if(exists('formiga.js')&&!read('formiga.js').includes("recordare/invocatio.js"))failures.push('La columna transversal formiga.js no carrega RECORDARE Invocatio.');if(exists('looperum/index.html')&&!read('looperum/index.html').includes('recordare/invocatio.js'))failures.push('Looperum no pot invocar RECORDARE.');if(exists('kreator1/index.html')&&!read('kreator1/index.html').includes('recordare/invocatio.js'))failures.push('KREATOR 1 no pot invocar RECORDARE.');
if(exists('looperum/index.html')){const l=read('looperum/index.html');for(const marker of ['inset:0;width:100%;height:100%', 'audio/*,video/*,.mp3,.m4a,.wav,.aac,.mp4,.mov,.m4v', 'LARGE_MEDIA_DECODE_BYTES', "media.setAttribute('webkit-playsinline','')", "media.preload='metadata'", 'media.controls=true', 'media.load()', 'Reproducció normal disponible'])if(!l.includes(marker))failures.push('Looperum iOS no preserva la reparació: '+marker);if(/FITITECA|Es materialitzarà com a porta pròpia|no inventem una ruta inexistent/.test(l))failures.push('Looperum conserva navegació provisional supersedida pel Portal multimèdia.');}

// ARCHIVUM · CUSTÒDIA 1.0: contracte, dos casos, mapa i interfície sense transferència binària
const custodyFiles=['governanca/ARCHIVUM_CUSTODIA_1.0.md','archivum/custodia/contracte-1.0.json','archivum/custodia/history-tales-v1.1-custody-v1.2.json','archivum/custodia/eco-01-cas-real-01.json','portal-multimedia/custodia.js'];
for(const file of custodyFiles)if(!exists(file))failures.push('Archivum Custòdia incomplet: falta '+file);
if(custodyFiles.every(exists)){
 let contract,ht,eco;try{contract=JSON.parse(read(custodyFiles[1]));ht=JSON.parse(read(custodyFiles[2]));eco=JSON.parse(read(custodyFiles[3]));}catch{failures.push('Archivum Custòdia conté JSON invàlid.');}
 if(contract){for(const state of ['repository_preserved','local_only','external_unverified','externally_verified','derivative_preserved','missing_original','not_materialized'])if(!contract.states.some(x=>x.id===state))failures.push('Contracte Custòdia: falta estat '+state);if(contract.binaryPolicy?.binaryTransferred!==false||contract.verification?.automaticPromotion!==false)failures.push('Contracte Custòdia pot transferir o promocionar automàticament.');}
 if(ht){if(ht.subject?.status!=='closed_audited'||ht.custodySummary?.binaryTransferred!==false||ht.recordVersion!=='1.2')failures.push('Custòdia History Tales no preserva tancament, límit binari o versió 1.2.');for(const state of ['repository_preserved','externally_verified','missing_original'])if(!ht.evidence.some(x=>x.custodyState===state))failures.push('Custòdia History Tales: falta '+state);const verifiedOriginals=ht.evidence.filter(x=>x.role==='original'&&x.custodyState==='externally_verified');if(verifiedOriginals.length!==5||verifiedOriginals.some(x=>x.locator?.provider!=='chatgpt_library'||!x.locator?.libraryFileId||x.verification?.kind!=='sha256'||!/^[a-f0-9]{64}$/.test(x.verification?.value||'')))failures.push('Custòdia History Tales no acredita cinc originals externs amb Library ID i SHA-256.');const temporal=ht.evidence.find(x=>x.id==='ht-07-temporal-binary');if(temporal?.custodyState!=='externally_verified'||temporal.locator?.provider!=='google_drive'||!temporal.locator?.fileId||temporal.verification?.kind!=='sha256_and_human_identification'||temporal.verification?.humanDecision!=='confirmed_as_HT-07'||!/^[a-f0-9]{64}$/.test(temporal.verification?.value||''))failures.push('Custòdia HT·07 no acredita Drive, SHA-256 i identificació humana.');if(!ht.provenance?.predecessor||!exists(ht.provenance.predecessor))failures.push('Custòdia History Tales 1.2 no preserva el predecessor.');}
 if(eco){if(eco.subject?.status!=='closed_real_execution'||eco.custodySummary?.capturesPreserved!=='3/3'||eco.custodySummary?.binaryTransferred!==false||eco.decision?.doNotRepeat!==true)failures.push('Custòdia ECO 01 no preserva execució, 3/3, no-transferència o no-repetició.');if(eco.evidence.filter(x=>x.role==='primary_audio'&&x.custodyState==='local_only').length!==3)failures.push('Custòdia ECO 01 no declara tres àudios local_only.');}
 const ui=read('portal-multimedia/custodia.js'),portal=read('portal-multimedia/index.html'),universe=read('universe/index.html'),pont=JSON.parse(read('pont-site.json'));
 for(const marker of ['#custodia','binaryTransferred','History Tales','ECO 01'])if(!ui.includes(marker))failures.push('Interfície Custòdia: falta '+marker);
 if(!portal.includes('./custodia.js'))failures.push('Portal no carrega Archivum Custòdia.');
 for(const marker of ['id="custodyBtn"','Archivum · Custòdia','../portal-multimedia/#custodia'])if(!universe.includes(marker))failures.push('Mapa general no exposa Custòdia: '+marker);
 if(pont.organs?.archivum?.binary_transfer!=='none')failures.push('Pont del Site no preserva Archivum sense transferència binària.');
}

// STRATUM 1.2: contracte canònic, transversalitat, rastre reversible i genealogia honesta
for(const file of ['stratum/index.html','stratum/stratum.js','stratum/invocatio.js','stratum/lineages.js','governanca/STRATUM_1.2.md'])if(!exists(file))failures.push('STRATUM incomplet: falta '+file);
if(exists('stratum/index.html')){const s=read('stratum/index.html');for(const marker of ['STRATUM 1.2','genealogies explícitament documentades','Trobar no equival a relacionar; relacionar no equival a decidir.','id="genealogies"','aria-modal="true"','./lineages.js','../governanca/STRATUM_1.2.md'])if(!s.includes(marker))failures.push('STRATUM UI no declara el contracte 1.2: '+marker);}
if(exists('stratum/stratum.js')){const s=read('stratum/stratum.js');for(const marker of ["kind:'stratum-excavation'","canonical:false","reversible:true","decided:false","codex:stratum-trace","'missing-stratum'","'insufficient-provenance'","governanca/STRATUM_1.2.md"])if(!s.includes(marker))failures.push('STRATUM excavació no preserva el contracte 1.2: '+marker);}
if(exists('stratum/lineages.js')){const l=read('stratum/lineages.js');for(const marker of ["status:'branching'","status:'active'","status:'uncertain'","evidence:'documented'",'ancestor','mutation','descendant','provenance'])if(!l.includes(marker))failures.push('STRATUM lineage incomplet: '+marker);if(/fetch\(|airtable\.com|apiKey|AIRTABLE_TOKEN/i.test(l))failures.push('STRATUM lineage client no pot fingir sincronització ni contenir credencials.');}
if(exists('stratum/invocatio.js')){const i=read('stratum/invocatio.js');for(const marker of ['codex:stratum-invoked','codex:stratum-trace','codex:stratum-returned','canonical:false','reversible:true','decided:false'])if(!i.includes(marker))failures.push('STRATUM Invocatio incomplet: '+marker);}
if(exists('governanca/STRATUM_1.2.md')){const g=read('governanca/STRATUM_1.2.md');for(const marker of ['# STRATUM 1.2','Trobar no equival a relacionar; relacionar no equival a decidir.','missing-stratum','insufficient-provenance','uncertain-lineage','no afirma','canonical:false'])if(!g.includes(marker))failures.push('Governança STRATUM 1.2 incompleta: '+marker);}
if(exists('formiga.js')){const f=read('formiga.js');if(!f.includes('stratum/invocatio.js'))failures.push('formiga.js no carrega STRATUM transversalment.');if(!f.includes('data-codex-loader'))failures.push('formiga.js no evita càrregues transversals duplicades.');}

// ECO 01 · Listen / Faber: arrel atribuïda, audible transversal i Travessa no auto-canònica
for(const file of ['arrels/michel-faber-listen-retorn.md','governanca/TANCAMENT_ESCOLTA_FABER_1.0.md','beta/travesses/eco-01/README.md','beta/travesses/eco-01/index.html','beta/travesses/eco-01/eco-01.js'])if(!exists(file))failures.push('ECO 01 incomplet: falta '+file);
if(exists('arrels/michel-faber-listen-retorn.md')){const a=read('arrels/michel-faber-listen-retorn.md');for(const marker of ['Michel Faber','metabolització operativa','propietat relacional, no un òrgan','Fins que no existeixi evidència primària real'])if(!a.includes(marker))failures.push('Arrel Faber no preserva autoria/Occam: '+marker);}
if(exists('beta/travesses/eco-01/index.html')){const e=read('beta/travesses/eco-01/index.html');for(const marker of ['ECO 01','FONT CONSTANT','same','different','unknown','Una decisió humana','eco-01.js'])if(!e.includes(marker))failures.push('ECO 01 UI no declara el contracte: '+marker);if(/autoplay|canonical\s*[:=]\s*true/i.test(e))failures.push('ECO 01 UI no pot autoexecutar ni canonitzar.');}
if(exists('beta/travesses/eco-01/eco-01.js')){const e=read('beta/travesses/eco-01/eco-01.js');for(const marker of ["constant:true","localOnly:true","kind:'relational-property'","material:false","binaryTransferred:false","canonical:false","navigator.mediaDevices?.getUserMedia","humanDecision"])if(!e.includes(marker))failures.push('ECO 01 runtime no preserva el contracte: '+marker);if(/fetch\(|XMLHttpRequest|sendBeacon|WebSocket/i.test(e))failures.push('ECO 01 no pot transferir binaris fora del dispositiu.');}
// KREATOR 1.1: ordre causal, sobirania humana i MASTER invocable en la travessa
for(const file of ['kreator1/index.html','kreator1/session-01.js','governanca/KREATOR1_ORDRE_CAUSAL_1.1.md'])if(!exists(file))failures.push('KREATOR 1.1 incomplet: falta '+file);
if(exists('kreator1/session-01.js')){const k=read('kreator1/session-01.js');for(const marker of ["const VERSION='1.1-causal'",'decideKreator1Session',"hasHumanAuthorization(session,'transform')",'MUTATIO requereix una decisió humana transform registrada abans de l’operació.','kreator1.human-decision.recorded','humanDecision.effect.initiated=true','La sessió no es pot tancar sense una decisió humana prèvia.'])if(!k.includes(marker))failures.push('KREATOR 1.1 motor no preserva el llindar causal: '+marker);}
if(exists('kreator1/index.html')){const k=read('kreator1/index.html');for(const marker of ['id="decisionStep"','id="transformStep"','id="finalStep"','../formiga.js','codex:master-decision','window.Kreator1SuggestedImpulse','Registrar decisió humana'])if(!k.includes(marker))failures.push('KREATOR 1.1 UI no preserva la travessa causal: '+marker);const d=k.indexOf('id="decisionStep"'),m=k.indexOf('id="transformStep"'),c=k.indexOf('id="finalStep"');if(d<0||m<0||c<0||!(d<m&&m<c))failures.push('KREATOR 1.1 mostra MUTATIO o tancament abans de la decisió humana.');}
if(exists('governanca/KREATOR1_ORDRE_CAUSAL_1.1.md')){const g=read('governanca/KREATOR1_ORDRE_CAUSAL_1.1.md');for(const marker of ['suggestedImpulse → humanDecision → MUTATIO','KREATOR RPG és l’evolució de KRATOR','MASTER situa','no produeix veritat, cànon, decisió ni execució automàtica','1.1-causal'])if(!g.includes(marker))failures.push('Governança KREATOR 1.1 incompleta: '+marker);}

// KREATOR RPG 0.4: evolució de KRATOR, DAUS configurables i efecte posterior a decisió
for(const file of ['experiments/kreator-rpg/index.html','experiments/kreator-rpg/rpg.js','experiments/kreator-rpg/README.md','experiments/kreator-rpg/ambience.js','experiments/kreator-rpg/spectrum-annalis.js','experiments/kreator-rpg/assets/allo-que-es-cou.mp3','experiments/kreator-rpg/seguiment/index.html','experiments/kreator-rpg/seguiment/seguiment.js','governanca/CONVIVIUM_KREATOR_COHORT_1.0.md'])if(!exists(file))failures.push('KREATOR RPG 0.4 / CONVIVIUM incomplet: falta '+file);
if(exists('experiments/kreator-rpg/index.html')){const r=read('experiments/kreator-rpg/index.html');for(const marker of ['KREATOR RPG 0.4','Cohort CONVIVIUM','EVOLUCIÓ DE KRATOR','DAUS d6–d9','KREATOR DECIDEIX','data-dice-preset="7,9"','id="faces1"','<option selected>7</option>','id="faces2"','<option selected>9</option>','id="invokeMaster"','../../formiga.js','id="decide" disabled','id="register" disabled','id="closeNoEffect" disabled','Invocatio Dock · una sola interfície','class="shell cockpit"','class="primary-rail"','class="shell instrument-rail"','Branques operatives clicables del Còdex','prefers-reduced-motion:reduce','CONTROL DE TRAVESSA · PRESSIÓ HUMANA','id="openRecordare"','id="openStratum"','.master-invoke,.recordare-invoke,.stratum-invoke{display:none!important}','data-axis="que"','data-axis="on"','QUÈ ↔ ON','id="axisSpace"','id="axisTrailStatus"','TRAJECTÒRIA REVERSIBLE','X: QUI–QUÈ · Y: QUAN–ON · Z: PER QUÈ–COM','<h2>CONVIVIUM</h2>','href="./seguiment/"','id="participantFocus"','../../universe/llenguatge/'])if(!r.includes(marker))failures.push('KREATOR RPG UI no preserva l’evolució causal, CONVIVIUM o el portal únic: '+marker);for(const route of ['../../universe/impuls.html','../../universe/llenguatge/','../../kreator1/','../../looperum/','../../fusio-total/#rosa','../../fusio-total/#z','../../fusio-total/#compost','../../cambra-nua-2/','../../inter-nos-creative/','../../recordare/','../../portal-multimedia/#custodia'])if(!r.includes(`href="${route}"`))failures.push('KREATOR RPG portal únic no preserva la ruta: '+route);if(r.includes('id="dockButton"'))failures.push('KREATOR RPG ha recuperat el dock flotant supersedit.');const d=r.indexOf('KREATOR DECIDEIX'),m=r.indexOf('<span class="step">MUTATIO</span>');if(d<0||m<0||d>m)failures.push('KREATOR RPG situa MUTATIO abans de la decisió.');}
if(exists('experiments/kreator-rpg/rpg.js')){const r=read('experiments/kreator-rpg/rpg.js');for(const marker of ["type:'human-decision'","type:'closure'","type:'decision-invalidated'","authorizedBy:{kind:'human-decision'","decision.effect.initiated=true","decision.effect.closedWithoutEffect=true","authority:'route-only'",'latestDiceForCycle()','routeMatches(decision)','invalidateDecisionOnRouteChange','codex:master-decision',"activeDecision()","d.humanDecision","que:['un rastre'","on:['al cos'",'selectAxis(axis)','renderAxisField()','plotCoordinates(dice)','drawAxisSpace(dice)',"spatialAxis={que:['x',1]","slice(-12)","event.type==='dice'","'02':{id:'KREATOR-02'","differenceClass:'audible'","differenceClass:'espacial'","differenceClass:'relacional'","differenceClass:'temporal'","codex-kreator-partida-${participant.id.slice(-2)}",'participant:{id:participant.id',"participant.id!=='KREATOR-01'&&!route.difference"])if(!r.includes(marker))failures.push('KREATOR RPG motor no preserva el llindar humà, la trajectòria XYZ o la cohort separada: '+marker);}
if(exists('experiments/kreator-rpg/seguiment/index.html')){const c=read('experiments/kreator-rpg/seguiment/index.html');for(const marker of ['CONVIVIUM · CAPA RELACIONAL TRANSVERSAL','FULL DE RUTA 1.0','ATLAS VISUAL','data-participant="02"','data-participant="03"','data-participant="04"','data-participant="05"','DIFERÈNCIA AUDIBLE','DIFERÈNCIA ESPACIAL','DIFERÈNCIA RELACIONAL','DIFERÈNCIA TEMPORAL','Retrodansa','Zajj‑viu','../?kreator=02','../?kreator=03','../?kreator=04','../?kreator=05','contactes fora del Site'])if(!c.includes(marker))failures.push('CONVIVIUM no preserva full de ruta, Atlas o cohort: '+marker);}
if(exists('experiments/kreator-rpg/seguiment/seguiment.js')){const c=read('experiments/kreator-rpg/seguiment/seguiment.js');for(const marker of ["const cohort=['02','03','04','05']","type==='movement'","type==='closure'","closed===cohort.length","localStorage.setItem(importKey(code)","localStorage.removeItem(importKey"] )if(!c.includes(marker))failures.push('Seguiment CONVIVIUM no preserva tancament local i reversible: '+marker);if(/fetch\(|XMLHttpRequest|sendBeacon|WebSocket/i.test(c))failures.push('CONVIVIUM no pot transmetre rastres ni contactes.');}
if(exists('experiments/kreator-rpg/ambience.js')){const a=read('experiments/kreator-rpg/ambience.js'),dock=read('experiments/kreator-rpg/index.html'),convivium=read('experiments/kreator-rpg/seguiment/index.html');for(const marker of ['data-ambience-toggle','data-ambience-audio','ambience.js','ALLÒ QUE ES COU'])if(!dock.includes(marker)||!convivium.includes(marker))failures.push('La matèria sonora no és compartida entre Dock i CONVIVIUM: '+marker);for(const marker of ["codex-kreator-ambience","audio.play()","writePreference('off')","targetVolume = 0.14"])if(!a.includes(marker))failures.push('La matèria sonora no preserva activació humana, silenci o volum baix: '+marker);if(/human-decision|decision\.effect|provenance|events\.push/.test(a))failures.push('La matèria sonora ambiental no pot entrar a la cadena causal ni al provenance.');}
if(exists('experiments/kreator-rpg/spectrum-annalis.js')){const s=read('experiments/kreator-rpg/spectrum-annalis.js'),dock=read('experiments/kreator-rpg/index.html');for(const marker of ['SPECTRUM ANNALIS','data-spectrum-canvas','accept="audio/*,video/*"','data-spectrum-transport','data-spectrum-clear','spectrum-annalis.js','prefers-reduced-motion:reduce'])if(!dock.includes(marker))failures.push('Spectrum Annalis no preserva receptor, control local o moviment reduït: '+marker);for(const marker of ['createAnalyser()','getByteFrequencyData','URL.createObjectURL(file)','URL.revokeObjectURL(objectUrl)',"file.type.startsWith('audio/')","file.type.startsWith('video/')"])if(!s.includes(marker))failures.push('Spectrum Annalis no analitza o no retira correctament la font local: '+marker);if(/fetch\(|XMLHttpRequest|sendBeacon|WebSocket|events\.push|human-decision|provenance/i.test(s))failures.push('Spectrum Annalis no pot transmetre, decidir ni escriure provenance.');}
if(exists('governanca/CONVIVIUM_KREATOR_COHORT_1.0.md')){const c=read('governanca/CONVIVIUM_KREATOR_COHORT_1.0.md');for(const marker of ['capa relacional transversal','No és un territori, un òrgan, una autoritat ni una memòria paral·lela','KREATOR RPG 02','KREATOR RPG 03','KREATOR RPG 04','KREATOR RPG 05','nova decisió humana','reunir no equival a fusionar'])if(!c.includes(marker))failures.push('Contracte CONVIVIUM incomplet: '+marker);}
if(failures.length){console.error('Validació del Còdex: ERROR');failures.forEach(x=>console.error(' - '+x));process.exit(1);}console.log('Validació del Còdex: OK');console.log('Scripts carregats:',loadedScriptRefs.length);console.log('Recursos offline verificats:',assetRefs.length);console.log('Rutes HTML verificades:',localRefs.length+fragmentRefs.length);console.log('RECORDARE 1.0: contracte transversal i localOnly verificat.');console.log('STRATUM 1.2: contracte canònic + buits explícits + rastre reversible + lineage honest verificats.');
