import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),failures=[];const normalizeLocal=ref=>ref.split(/[?#]/,1)[0].replace(/^\.\//,'');
const app=read('app.js');const scriptRefs=[...app.matchAll(/'\.\/(.+?\.js)'/g)].map(m=>m[1]),loadedScriptRefs=scriptRefs.filter(ref=>ref!=='sw.js');for(const ref of scriptRefs)if(!exists(ref))failures.push('app.js referencia un script inexistent: '+ref);
const sw=read('sw.js');const assetRefs=[...sw.matchAll(/'\.\/(.*?)'/g)].map(m=>m[1]).filter(Boolean);for(const ref of assetRefs)if(ref&&ref!=='.'&&!exists(ref))failures.push('sw.js referencia un recurs inexistent: '+ref);
const html=read('index.html');for(const marker of ['class="threshold"','class="enter"','href="./universe/"','formiga.css','formiga.js'])if(!html.includes(marker))failures.push('El llindar canònic no conté el marcador actual: '+marker);
if(!exists('universe/index.html'))failures.push('Falta la navegació presencial universe/index.html.');else{const universe=read('universe/index.html');for(const id of ['stage','organ','trace','ant','returnText'])if(!universe.includes('id="'+id+'"')&&!universe.includes("id='"+id+"'"))failures.push('La navegació presencial no conté #'+id);}
const localRefs=[...html.matchAll(/(?:href|src)=["']([^"']+)["']/g)].map(m=>m[1]).filter(ref=>!ref.startsWith('#')&&!/^(?:https?:|data:|mailto:|tel:)/.test(ref));for(const ref of localRefs){const target=normalizeLocal(ref);if(target&&!exists(target))failures.push('index.html referencia un recurs inexistent: '+ref);}const fragmentRefs=[...html.matchAll(/href=["']#([^"']+)["']/g)].map(m=>m[1]);for(const id of fragmentRefs)if(!html.includes('id="'+id+'"')&&!html.includes("id='"+id+"'"))failures.push('index.html referencia un fragment inexistent: #'+id);
let manifest;try{manifest=JSON.parse(read('manifest.webmanifest'))}catch{failures.push('manifest.webmanifest no és JSON vàlid.');}if(manifest){if(manifest.start_url!=='./'||manifest.scope!=='./')failures.push('El manifest ha de mantenir start_url i scope relatius a l’arrel canònica.');for(const icon of manifest.icons||[]){const target=normalizeLocal(icon.src||'');if(!target||!exists(target))failures.push('El manifest referencia una icona inexistent: '+(icon.src||'(buida)'));}}for(const ref of loadedScriptRefs)if(!assetRefs.includes(ref))failures.push('El mode offline no inclou el script carregat: '+ref);for(const ref of localRefs.map(normalizeLocal).filter(Boolean))if(!assetRefs.includes(ref)&&ref!=='sw.js')failures.push('El mode offline no inclou el recurs de la portada: '+ref);
for(const file of ['governanca/ARQUITECTURA.md','governanca/FUSIO_REPOSITORIS.md'])if(/`Animic-Protein\/Animic-Protein`/.test(read(file)))failures.push(file+' encara declara el repositori previ com a tronc canònic.');if(!exists('LICENSE.md'))failures.push('Falta la llicència canònica LICENSE.md.');else{const license=read('LICENSE.md');for(const marker of ['LICENSE_STATUS: FINAL-RR-1.0','Copyright © 2026 Dàrius Balboa','permís escrit previ','Contribucions'])if(!license.includes(marker))failures.push('LICENSE.md no conté el marcador canònic: '+marker);if(/LICENSE_STATUS:\s*PENDING/i.test(license))failures.push('La llicència encara consta com a pendent.');}if(!exists('governanca/DECISIO_LLICENCIA_2026-08-27.md'))failures.push('Falta l’acta de decisió de la llicència definitiva.');const allJs=fs.readdirSync(root).filter(n=>n.endsWith('.js'));if(!allJs.includes('core.js')||!allJs.includes('germinacio.js'))failures.push('Falten fitxers crítics del nucli.');
for(const file of ['recordare/index.html','recordare/recordare.js','recordare/invocatio.js','governanca/RECORDARE_1.0.md'])if(!exists(file))failures.push('RECORDARE incomplet: falta '+file);if(exists('recordare/recordare.js')){const r=read('recordare/recordare.js');for(const marker of ["getUserMedia({audio:true})","localOnly:true","canonical:false","binaryTransferred:false","codex:recordare-metadata-ready"])if(!r.includes(marker))failures.push('RECORDARE no preserva el contracte: '+marker);if(/airtable\.com|apiKey|AIRTABLE_TOKEN/i.test(r))failures.push('RECORDARE client no pot contenir connexió o credencials Airtable.');}if(exists('recordare/invocatio.js')&&!read('recordare/invocatio.js').includes('codex:recordare-metadata-ready'))failures.push('Invocatio no retorna les metadades preparades al context invocador.');if(exists('formiga.js')&&!read('formiga.js').includes("recordare/invocatio.js"))failures.push('La columna transversal formiga.js no carrega RECORDARE Invocatio.');if(exists('looperum/index.html')&&!read('looperum/index.html').includes('recordare/invocatio.js'))failures.push('Looperum no pot invocar RECORDARE.');if(exists('kreator1/index.html')&&!read('kreator1/index.html').includes('recordare/invocatio.js'))failures.push('KREATOR 1 no pot invocar RECORDARE.');
if(exists('looperum/index.html')){const l=read('looperum/index.html');for(const marker of ['inset:0;width:100%;height:100%', 'audio/*,video/*,.mp3,.m4a,.wav,.aac,.mp4,.mov,.m4v', 'LARGE_MEDIA_DECODE_BYTES', "media.setAttribute('webkit-playsinline','')", "media.preload='metadata'", 'media.controls=true', 'media.load()', 'Reproducció normal disponible'])if(!l.includes(marker))failures.push('Looperum iOS no preserva la reparació: '+marker);if(/FITITECA|Es materialitzarà com a porta pròpia|no inventem una ruta inexistent/.test(l))failures.push('Looperum conserva navegació provisional supersedida pel Portal multimèdia.');}
// STRATUM 1.2: contracte canònic, transversalitat, rastre reversible i genealogia honesta
for(const file of ['stratum/index.html','stratum/stratum.js','stratum/invocatio.js','stratum/lineages.js','governanca/STRATUM_1.2.md'])if(!exists(file))failures.push('STRATUM incomplet: falta '+file);
if(exists('stratum/index.html')){const s=read('stratum/index.html');for(const marker of ['STRATUM 1.2','genealogies explícitament documentades','Trobar no equival a relacionar; relacionar no equival a decidir.','id="genealogies"','aria-modal="true"','./lineages.js','../governanca/STRATUM_1.2.md'])if(!s.includes(marker))failures.push('STRATUM UI no declara el contracte 1.2: '+marker);}
if(exists('stratum/stratum.js')){const s=read('stratum/stratum.js');for(const marker of ["kind:'stratum-excavation'","canonical:false","reversible:true","decided:false","codex:stratum-trace","'missing-stratum'","'insufficient-provenance'","governanca/STRATUM_1.2.md"])if(!s.includes(marker))failures.push('STRATUM excavació no preserva el contracte 1.2: '+marker);}
if(exists('stratum/lineages.js')){const l=read('stratum/lineages.js');for(const marker of ["status:'branching'","status:'active'","status:'uncertain'","evidence:'documented'",'ancestor','mutation','descendant','provenance'])if(!l.includes(marker))failures.push('STRATUM lineage incomplet: '+marker);if(/fetch\(|airtable\.com|apiKey|AIRTABLE_TOKEN/i.test(l))failures.push('STRATUM lineage client no pot fingir sincronització ni contenir credencials.');}
if(exists('stratum/invocatio.js')){const i=read('stratum/invocatio.js');for(const marker of ['codex:stratum-invoked','codex:stratum-trace','codex:stratum-returned','canonical:false','reversible:true','decided:false'])if(!i.includes(marker))failures.push('STRATUM Invocatio incomplet: '+marker);}
if(exists('governanca/STRATUM_1.2.md')){const g=read('governanca/STRATUM_1.2.md');for(const marker of ['# STRATUM 1.2','Trobar no equival a relacionar; relacionar no equival a decidir.','missing-stratum','insufficient-provenance','uncertain-lineage','no afirma','canonical:false'])if(!g.includes(marker))failures.push('Governança STRATUM 1.2 incompleta: '+marker);}
if(exists('formiga.js')){const f=read('formiga.js');if(!f.includes('stratum/invocatio.js'))failures.push('formiga.js no carrega STRATUM transversalment.');if(!f.includes('data-codex-loader'))failures.push('formiga.js no evita càrregues transversals duplicades.');}

// ECO 01 · Listen / Faber: arrel atribuïda, audible transversal i Travessa no auto-canònica
for(const file of ['arrels/michel-faber-listen-retorn.md','governanca/TANCAMENT_ESCOLTA_FABER_1.0.md','beta/travesses/eco-01/README.md','beta/travesses/eco-01/index.html','beta/travesses/eco-01/eco-01.js'])if(!exists(file))failures.push('ECO 01 incomplet: falta '+file);
if(exists('arrels/michel-faber-listen-retorn.md')){const a=read('arrels/michel-faber-listen-retorn.md');for(const marker of ['Michel Faber','metabolització operativa','propietat relacional, no un òrgan','Fins que no existeixi evidència primària real'])if(!a.includes(marker))failures.push('Arrel Faber no preserva autoria/Occam: '+marker);}
if(exists('beta/travesses/eco-01/index.html')){const e=read('beta/travesses/eco-01/index.html');for(const marker of ['ECO 01','FONT CONSTANT','same','different','unknown','Una decisió humana','eco-01.js'])if(!e.includes(marker))failures.push('ECO 01 UI no declara el contracte: '+marker);if(/autoplay|canonical\s*[:=]\s*true/i.test(e))failures.push('ECO 01 UI no pot autoexecutar ni canonitzar.');}
if(exists('beta/travesses/eco-01/eco-01.js')){const e=read('beta/travesses/eco-01/eco-01.js');for(const marker of ["constant:true","localOnly:true","kind:'relational-property'","material:false","binaryTransferred:false","canonical:false","navigator.mediaDevices?.getUserMedia","humanDecision"])if(!e.includes(marker))failures.push('ECO 01 runtime no preserva el contracte: '+marker);if(/fetch\(|XMLHttpRequest|sendBeacon|indexedDB/i.test(e))failures.push('ECO 01 no pot transferir ni persistir binaris.');}
if(failures.length){console.error('Validació del Còdex: ERROR');failures.forEach(x=>console.error(' - '+x));process.exit(1);}console.log('Validació del Còdex: OK');console.log('Scripts carregats:',loadedScriptRefs.length);console.log('Recursos offline verificats:',assetRefs.length);console.log('Rutes HTML verificades:',localRefs.length+fragmentRefs.length);console.log('RECORDARE 1.0: contracte transversal i localOnly verificat.');console.log('STRATUM 1.2: contracte canònic + buits explícits + rastre reversible + lineage honest verificats.');