(()=>{
'use strict';
const LINEAGES=[
 {id:'recY3xc1Gz1XDYYuc',label:'Ordre/caos → glossa',status:'branching',ancestor:{id:'recMD6ZOkMw8HF4a7',text:'Tot ordre esdevé caos natural i, naturalment, el caos esdevé el seu ordre.'},mutation:'La formulació canònica sobre l’alternança ordre/caos genera una glossa emergent que redefineix el caos com a ordre encara no reconegut.',descendant:{id:'recX5EDzkc8rqnDLL',text:'El caos no és l’absència d’ordre: és l’ordre abans de reconèixer-se.'},origin:'conversation-history#AEQ-I'},
 {id:'recZx1KhyoW9iYPu1',label:'Impuls → MASTER · INVOCATIO',status:'active',ancestor:{id:'recrV3K7YX5W3uukW',text:'El Còdex proposa. La persona decideix. La discrepància roman oberta. L’experiència transforma. El Còdex recorda.'},mutation:'La formulació general «El Còdex proposa…» es distribueix en funcions diferenciades: IMPULS apareix, MASTER s’invoca, LOCUTUS formula, KREATOR decideix i MUTATIO transforma.',descendant:{id:'reckvcy7oGLnPPGif',text:'IMPULS apareix. MASTER és invocat. LOCUTUS formula. KREATOR decideix. MUTATIO transforma. El Còdex recorda.'},origin:'governanca/MASTER_INVOCATIO_1.0.md'},
 {id:'recvRz2DzizCEFV03',label:'Error Fèrtil → silenci operatiu',status:'uncertain',ancestor:{id:'recMIlHel8n97z0St',text:'Quan una continuïtat falla, no la reparis immediatament: escolta què queda sostenint el temps.'},mutation:'La regla de no reparar immediatament una continuïtat fallida ressona després com la possibilitat de considerar el silenci un estat operatiu, sense convertir aquesta ressonància en equivalència.',descendant:{id:'rec7pNWz6Qr62QSE7',text:'El silenci també és un estat operatiu.'},origin:'archivum/archeologia-verbal-1.0'}
];
const norm=s=>String(s||'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function relevant(q){const terms=norm(q).split(/\s+/).filter(t=>t.length>2);if(!terms.length)return[];return LINEAGES.filter(l=>terms.some(t=>norm([l.label,l.ancestor.text,l.mutation,l.descendant.text,l.origin].join(' ')).includes(t)));}
function render(query){
 const host=document.querySelector('#genealogies');if(!host)return[];const matches=relevant(query);host.hidden=!matches.length;
 if(!matches.length){host.innerHTML='';window.dispatchEvent(new CustomEvent('codex:stratum-lineages-rendered',{detail:{query,count:0,statuses:[],uncertain:false}}));return[];}
 host.innerHTML=`<div class="section-head"><p class="ey">Genealogia documentada</p><p>${matches.length} línia${matches.length===1?'':'s'} amb ancestor, mutation, descendant i provenance.</p></div><div class="lineage-list">${matches.map(l=>`<article class="lineage-card lineage-${esc(l.status)}"><header><span class="lineage-status">${esc(l.status)}</span><strong>${esc(l.label)}</strong></header><div class="lineage-flow"><div class="lineage-node"><small>ancestor</small><p>${esc(l.ancestor.text)}</p></div><div class="lineage-mutation"><small>mutation</small><p>${esc(l.mutation)}</p></div><div class="lineage-node"><small>descendant</small><p>${esc(l.descendant.text)}</p></div></div><p class="prov">provenance · ${esc(l.origin)} · lineage ${esc(l.id)}</p>${l.status==='uncertain'?'<p class="uncertainty">uncertain-lineage · ressonància documentada, no equivalència.</p>':''}</article>`).join('')}</div>`;
 const detail={query,count:matches.length,statuses:matches.map(x=>x.status),uncertain:matches.some(x=>x.status==='uncertain')};window.dispatchEvent(new CustomEvent('codex:stratum-lineages-rendered',{detail}));return matches;
}
window.addEventListener('codex:stratum-excavated',e=>render(e.detail?.query||''));
window.StratumLineages={all:()=>LINEAGES.map(x=>JSON.parse(JSON.stringify(x))),relevant,render};
})();