(()=>{
'use strict';
const LINEAGES=[
 {id:'recY3xc1Gz1XDYYuc',label:'Ordre/caos → glossa',status:'branching',ancestor:{id:'recMD6ZOkMw8HF4a7',text:'Tot ordre esdevé caos natural i, naturalment, el caos esdevé el seu ordre.'},mutation:'La formulació canònica sobre l’alternança ordre/caos genera una glossa emergent que redefineix el caos com a ordre encara no reconegut.',descendant:{id:'recX5EDzkc8rqnDLL',text:'El caos no és l’absència d’ordre: és l’ordre abans de reconèixer-se.'},origin:'conversation-history#AEQ-I'},
 {id:'recZx1KhyoW9iYPu1',label:'Impuls → MASTER · INVOCATIO',status:'active',ancestor:{id:'recrV3K7YX5W3uukW',text:'El Còdex proposa. La persona decideix. La discrepància roman oberta. L’experiència transforma. El Còdex recorda.'},mutation:'La formulació general «El Còdex proposa…» es distribueix en funcions diferenciades: IMPULS apareix, MASTER s’invoca, LOCUTUS formula, KREATOR decideix i MUTATIO transforma.',descendant:{id:'reckvcy7oGLnPPGif',text:'IMPULS apareix. MASTER és invocat. LOCUTUS formula. KREATOR decideix. MUTATIO transforma. El Còdex recorda.'},origin:'governanca/MASTER_INVOCATIO_1.0.md'},
 {id:'recvRz2DzizCEFV03',label:'Error Fèrtil → silenci operatiu',status:'uncertain',ancestor:{id:'recMIlHel8n97z0St',text:'Quan una continuïtat falla, no la reparis immediatament: escolta què queda sostenint el temps.'},mutation:'La regla de no reparar immediatament una continuïtat fallida ressona després com la possibilitat de considerar el silenci un estat operatiu, sense convertir aquesta ressonància en equivalència.',descendant:{id:'rec7pNWz6Qr62QSE7',text:'El silenci també és un estat operatiu.'},origin:'archivum/archeologia-verbal-1.0'}
];
const norm=s=>String(s||'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function relevant(q){const terms=norm(q).split(/\s+/).filter(t=>t.length>2);if(!terms.length)return[];return LINEAGES.filter(l=>terms.some(t=>norm([l.label,l.ancestor.text,l.mutation,l.descendant.text,l.origin].join(' ')).includes(t)));}
function render(query){const old=document.querySelector('#stratum-lineages');if(old)old.remove();const matches=relevant(query);if(!matches.length)return;const host=document.querySelector('#results');if(!host)return;const section=document.createElement('section');section.id='stratum-lineages';section.className='results';section.style.marginTop='18px';section.innerHTML='<div class="empty"><strong>Genealogies verificades</strong><br><small>Una genealogia mostra un rastre documentat; el seu estat no decideix quin estrat és correcte.</small></div>'+matches.map(l=>`<article class="card"><div class="meta"><span class="tag">Lineage</span><span class="tag">${esc(l.status)}</span></div><p class="context"><strong>${esc(l.label)}</strong></p><p class="quote">${esc(l.ancestor.text)}</p><p class="context">↓ <strong>mutation</strong> · ${esc(l.mutation)}</p><p class="quote">${esc(l.descendant.text)}</p><p class="prov">provenance · ${esc(l.origin)} · lineage ${esc(l.id)} · ancestor ${esc(l.ancestor.id)} · descendant ${esc(l.descendant.id)}</p>${l.status==='uncertain'?'<p class="context">uncertain-lineage · ressonància documentada, no equivalència.</p>':''}</article>`).join('');host.after(section);}
window.addEventListener('codex:stratum-excavated',e=>render(e.detail?.query||''));
window.StratumLineages={all:()=>LINEAGES.map(x=>JSON.parse(JSON.stringify(x))),render};
})();