(()=>{
'use strict';
const CORPUS=[
{text:'El Còdex no representa el pensament: assaja condicions perquè el pensament es transformi.',state:'canonical',stratum:'Sediment verbal',context:'Ecosistema del Pensament',origin:'Archivum · sediment verbal',certainty:'declared'},
{text:'Quan una continuïtat falla, no la reparis immediatament: escolta què queda sostenint el temps.',state:'provisional',stratum:'Sediment verbal',context:'Error fèrtil I · Compost',origin:'Archivum · sediment verbal',certainty:'provisional'},
{text:'El Còdex proposa. La persona decideix. La discrepància roman oberta. L’experiència transforma. El Còdex recorda.',state:'canonical',stratum:'Sediment verbal',context:'Impuls Operatiu 1.2',origin:'Archivum · sediment verbal',certainty:'declared'},
{text:'Percebre no equival a interpretar; interpretar no equival a decidir; proposar no equival a executar.',state:'emergent',stratum:'Sediment verbal',context:'Impuls / KREATOR',origin:'Archivum · sediment verbal',certainty:'emergent'},
{text:'La discrepància entre la proposta del Còdex i la decisió humana es conserva sense decidir immediatament qui tenia raó.',state:'emergent',stratum:'Sediment verbal',context:'Impuls / decisió humana',origin:'Archivum · sediment verbal',certainty:'emergent'},
{text:'Ruta simple, directa i reversible; una desviació només es justifica per una funció perceptible o operativa clara.',state:'canonical',stratum:'Vocabulari Viu',context:'Occam',origin:'Archivum · sediment verbal',certainty:'declared'},
{text:'Tot ordre esdevé caos natural i, naturalment, el caos esdevé el seu ordre.',state:'canonical',stratum:'Sediment verbal',context:'Ordre / caos',origin:'Archivum · sediment verbal',certainty:'declared'},
{text:'El caos no és l’absència d’ordre: és l’ordre abans de reconèixer-se.',state:'emergent',stratum:'Glossae Vivens',context:'Glossa d’ordre / caos',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'IMPULS apareix. MASTER és invocat. LOCUTUS formula. KREATOR decideix. MUTATIO transforma. El Còdex recorda.',state:'canonical',stratum:'Sediment verbal',context:'Arquitectura constitucional · termes: IMPULS, MASTER, LOCUTUS, KREATOR, MUTATIO',origin:'Archivum · sediment verbal',certainty:'declared'},
{text:'RECORDARE captura. Archivum conserva. La memòria relaciona. KREATOR decideix què significa.',state:'provisional',stratum:'Sediment verbal',context:'RECORDARE · Archivum · KREATOR',origin:'Governança RECORDARE 1.0',certainty:'provisional'},
{text:'Ítaca no era un lugar, era un temblor.',state:'emergent',stratum:'Sediment verbal',context:'Ítaca · Teatre del Tremolor · Silenci',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'Creativitum nunc Pacevem.',state:'emergent',stratum:'Latinismes',context:'Brodsky · Creativitat',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'No fusionaria el contingut financer amb l’univers artístic; fusionaria la gramàtica operativa.',state:'emergent',stratum:'Glossae Vivens',context:'Longbridge · metabolització',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'El Looperum ha de poder crear bucles a partir d’altres fonts o del seu propi Arxiu, i el seu comportament ha de ser el mateix Còdex.',state:'emergent',stratum:'Vocabulari Viu',context:'Looperum · Archivum',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'La desaparició d’una direcció modifica realment l’escolta i una decisió posterior.',state:'emergent',stratum:'Sediment verbal',context:'Travessa β·02',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'Qualsevol persona amb impuls de crear.',state:'emergent',stratum:'Sediment verbal',context:'Guia personal',origin:'Arqueologia verbal 1.0',certainty:'approved'},
{text:'La Formiga apareix quan ens apropem a alguna cosa que pot funcionar.',state:'emergent',stratum:'Vocabulari Viu',context:'Formiga · relacions',origin:'Arqueologia verbal 1.0',certainty:'recovered'},
{text:'Una relació no és una fusió.',state:'emergent',stratum:'Glossae Vivens',context:'INTER NOS · navegació relacional',origin:'Arqueologia verbal 1.0',certainty:'condensed'},
{text:'El silenci també és un estat operatiu.',state:'emergent',stratum:'Vocabulari Viu',context:'quiet · universe/impuls.js',origin:'GitHub + Arqueologia verbal 1.0',certainty:'confirmed'},
{text:'La convergència no és certesa.',state:'emergent',stratum:'Glossae Vivens',context:'Formiga · CONFLUENTIA',origin:'GitHub + Arqueologia verbal 1.0',certainty:'confirmed'},
{text:'STRATUM',state:'provisional',stratum:'Latinismes',context:'Instrumentum Archaeologiae · Corpus instrumentalis',origin:'governanca/STRATUM_1.0.md',certainty:'constituted'},
{text:'Excavar és recuperar sense substituir, relacionar sense fusionar i mostrar la genealogia sense decidir-ne el sentit.',state:'provisional',stratum:'Sediment verbal',context:'STRATUM 1.0',origin:'governanca/STRATUM_1.0.md',certainty:'constituted'}
];
const normalize=s=>(s||'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const strata=[...new Set(CORPUS.map(x=>x.stratum))];let active='Tots',lastFound=[],mediaUrls=[];
const $=s=>document.querySelector(s),results=$('#results'),status=$('#status'),q=$('#q'),bar=$('#strata'),readBtn=$('#readBtn');
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderFilters(){bar.innerHTML=['Tots',...strata].map(s=>`<button type="button" data-s="${esc(s)}" aria-pressed="${s===active}">${esc(s)}</button>`).join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.s;renderFilters();if(q.value.trim())excavate();});}
function score(item,terms,query){const text=normalize(item.text),context=normalize(item.context),origin=normalize(item.origin),stratum=normalize(item.stratum);let n=0;if(query&&text.includes(query))n+=6;if(query&&context.includes(query))n+=4;terms.forEach(t=>{if(text.includes(t))n+=3;if(context.includes(t))n+=2;if(origin.includes(t)||stratum.includes(t))n+=1;});return n;}
function excavate(){const raw=q.value.trim(),query=normalize(raw),terms=query.split(/\s+/).filter(Boolean);status.dataset.busy='true';status.textContent='Excavant…';if(!terms.length){lastFound=[];results.innerHTML='<div class="empty">Dona a STRATUM un mot, una frase, un instrument o un rastre per començar.</div>';status.textContent='No hi ha consulta: STRATUM no inventa què vols excavar.';status.dataset.busy='false';readBtn.disabled=true;q.focus();return;}lastFound=CORPUS.map(x=>({...x,_score:score(x,terms,query)})).filter(x=>x._score>0&&(active==='Tots'||x.stratum===active)).sort((a,b)=>b._score-a._score||a.text.localeCompare(b.text,'ca'));status.textContent=`${lastFound.length} estrat${lastFound.length===1?'':'s'} recuperat${lastFound.length===1?'':'s'} · “${raw}” · cap resultat modifica l’original.`;status.dataset.busy='false';results.innerHTML=lastFound.length?lastFound.map(x=>`<article class="card"><div class="meta"><span class="tag">${esc(x.stratum)}</span><span class="tag state-${esc(x.state)}">${esc(x.state)}</span><span class="tag">${esc(x.certainty)}</span></div><p class="quote">${esc(x.text)}</p><p class="context">${esc(x.context)}</p><p class="prov">provenance · ${esc(x.origin)}</p></article>`).join(''):'<div class="empty">Cap estrat rastrejable. STRATUM no omple el buit: prova una altra formulació o incorpora provenance abans de relacionar.</div>';readBtn.disabled=!lastFound.length;window.dispatchEvent(new CustomEvent('codex:stratum-excavated',{detail:{query:raw,count:lastFound.length,stratum:active}}));}
function readExcavation(){if(!lastFound.length)return;const text=`STRATUM. ${lastFound.length} estrats recuperats. `+lastFound.slice(0,6).map((x,i)=>`${i+1}. ${x.text}. Context: ${x.context}.`).join(' ');if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ca-ES';speechSynthesis.speak(u);}else status.textContent='Aquest navegador no ofereix lectura de veu. Els estrats continuen visibles.';}
function clearMediaUrls(){mediaUrls.forEach(URL.revokeObjectURL);mediaUrls=[];}
function openPhotoLibrary(){const input=$('#photoInput');input.value='';input.click();}
function loadMedia(files){clearMediaUrls();const panel=$('#mediaPanel'),grid=$('#mediaGrid'),mediaStatus=$('#mediaStatus');const list=[...files];if(!list.length){panel.hidden=true;return;}panel.hidden=false;mediaStatus.textContent=`${list.length} element${list.length===1?'':'s'} seleccionat${list.length===1?'':'s'} · només en aquesta sessió.`;grid.innerHTML='';list.forEach((file,i)=>{const url=URL.createObjectURL(file);mediaUrls.push(url);const card=document.createElement('article');card.className='media-item';const visual=file.type.startsWith('video/')?document.createElement('video'):document.createElement('img');visual.src=url;if(visual.tagName==='VIDEO'){visual.controls=true;visual.preload='metadata';}else visual.alt=file.name||`Imatge ${i+1}`;const p=document.createElement('p');p.textContent=`${file.name||'sense nom'} · ${file.type||'tipus desconegut'} · ${Math.max(1,Math.round(file.size/1024))} KB`;const b=document.createElement('button');b.type='button';b.textContent='Excavar aquest rastre';b.onclick=()=>{q.value=(file.name||'fototeca').replace(/[_-]+/g,' ').replace(/\.[^.]+$/,'');active='Tots';renderFilters();excavate();status.textContent+=` · font local: Fototeca #${i+1}.`;};card.append(visual,p,b);grid.append(card);});window.dispatchEvent(new CustomEvent('codex:stratum-media-selected',{detail:{count:list.length,sourceKind:'media',localOnly:true}}));}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();excavate();});$('#excavateBtn').addEventListener('click',()=>setTimeout(()=>{if(document.activeElement?.id==='excavateBtn'&&status.dataset.busy!=='true'){}},0));$('#photoBtn').addEventListener('click',openPhotoLibrary);$('#photoInput').addEventListener('change',e=>loadMedia(e.target.files));readBtn.addEventListener('click',readExcavation);q.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();excavate();}});
const params=new URLSearchParams(location.search);if(params.get('q'))q.value=params.get('q');renderFilters();if(q.value)excavate();window.addEventListener('pagehide',clearMediaUrls);
window.Stratum={excavate:(query)=>{q.value=query||'';excavate();},corpus:()=>CORPUS.map(x=>({...x})),openPhotoLibrary};
})();
